# Generated by Django 3.1.4 on 2020-12-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShtuffList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('images', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Shtuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('shtuff_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shtufflist')),
            ],
        ),
    ]
