# Generated by Django 3.1.4 on 2020-12-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shtufflist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shtufflist',
            old_name='images',
            new_name='image',
        ),
    ]
