# Generated by Django 3.1.4 on 2020-12-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201223_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shtufflist',
            old_name='image',
            new_name='images',
        ),
    ]
