# Generated by Django 3.1.4 on 2020-12-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201224_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shtufflist',
            old_name='images',
            new_name='image',
        ),
    ]
